#!/usr/bin/python
# -*- coding: utf-8 -*-
import math, signal, sys, os, time
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setup(24, GPIO.IN)
vuelta = 0
max = 10
while vuelta < max:
        if GPIO.input(24) == False:
                print "No detecta"
                print vuelta
                time.sleep(1)
        else:
                print "Detecta"
                vuelta = vuelta + 1
                print vuelta
                time.sleep(1)
print "Bateria llena"

