#!/usr/bin/python
# -*- coding: utf-8 -*-

# Internet de las Cosas - http://internetdelascosas.cl
#
# Descripcion  : Programa que permite obtener la lectura de un se$
# Lenguaje     : Python
# Autor        : Jose Zorrilla <jzorrilla@iot.cl>
# Dependencias : Libreria de Adafruit https://github.com/adafruit$
# Web          : http://internetdelascosas.cl/

# Importa las librerias necesarias 
import RPi.GPIO as GPIO
import sys
import time
import Adafruit_DHT
import datetime

# Configuracion del tipo de sensor DHT
sensor = Adafruit_DHT.DHT11
 

# Configuracion del puerto GPIO al cual esta conectado  (GPIO 23)
pin = 23
#instance = dht11.DHT11(pin=23)

# Intenta ejecutar las siguientes instrucciones, si falla va a la$
while True:
        # Obtiene la humedad y la temperatura desde el sensor
        humedad, temperatura = Adafruit_DHT.read_retry(sensor, pi$
        # Imprime en la consola las variables temperatura y humed$
        print('Temperatura={0:0.1f}*  Humedad={1:0.1f}%'.format(t$
        if (temperatura) >= 22:
                humedad, temperatura = Adafruit_DHT.read_retry(se$
                GPIO.setmode(GPIO.BCM)
                GPIO.setup(17, GPIO.OUT)
                GPIO.output(17,True)
                print('El ventilador esta activado')
        if (temperatura) <= 21:
                humedad, temperatura = Adafruit_DHT.read_retry(se$
                GPIO.setmode(GPIO.BCM)
                GPIO.setup(17, GPIO.OUT)
                GPIO.output(17,False)
                print('El ventilador esta desactivado')

GPIO.output(17,False)

